In [1]:
import pandas as pd
import numpy as np

In [2]:
v = pd.read_csv('final_variable.csv')

In [3]:
selected_col = [
'Recnum',
'Merch_description_part_count0__max',
 'Merchnum_count0__max',
 'Merchnum_count1__max',
 'Merchnum_count1__sum',
 'Merchnum_count3__max',
 'cardnum-merch_description_part_count14__max',
 'cardnum-merch_description_part_count14__sum',
 'cardnum-merch_description_part_count30__max',
 'cardnum-merch_description_part_count3__sum',
 'cardnum-merch_state_count14__max',
 'cardnum-merch_state_count30__max',
 'cardnum-merch_state_merch_zip_count30__max',
 'cardnum-merch_state_merch_zip_count3__sum',
 'cardnum-merch_zip_count14__max',
 'cardnum-merchnum_count14__max',
 'cardnum-merchnum_count14__sum',
 'cardnum-merchnum_count1__max',
 'cardnum-merchnum_count30__max',
 'cardnum-merchnum_count3__max',
 'cardnum-merchnum_count3__sum',
'Fraud']

In [4]:
df = v[selected_col]

In [5]:
selected = ['Merch_description_part_count0__max',
 'Merchnum_count0__max',
 'Merchnum_count1__max',
 'Merchnum_count1__sum',
 'Merchnum_count3__max',
 'cardnum-merch_description_part_count14__max',
 'cardnum-merch_description_part_count14__sum',
 'cardnum-merch_description_part_count30__max',
 'cardnum-merch_description_part_count3__sum',
 'cardnum-merch_state_count14__max',
 'cardnum-merch_state_count30__max',
 'cardnum-merch_state_merch_zip_count30__max',
 'cardnum-merch_state_merch_zip_count3__sum',
 'cardnum-merch_zip_count14__max',
 'cardnum-merchnum_count14__max',
 'cardnum-merchnum_count14__sum',
 'cardnum-merchnum_count1__max',
 'cardnum-merchnum_count30__max',
 'cardnum-merchnum_count3__max',
 'cardnum-merchnum_count3__sum']

In [6]:
df.head()

,Recnum,Merch_description_part_count0__max,Merchnum_count0__max,Merchnum_count1__max,Merchnum_count1__sum,Merchnum_count3__max,cardnum-merch_description_part_count14__max,cardnum-merch_description_part_count14__sum,cardnum-merch_description_part_count30__max,cardnum-merch_description_part_count3__sum,...,cardnum-merch_state_merch_zip_count30__max,cardnum-merch_state_merch_zip_count3__sum,cardnum-merch_zip_count14__max,cardnum-merchnum_count14__max,cardnum-merchnum_count14__sum,cardnum-merchnum_count1__max,cardnum-merchnum_count30__max,cardnum-merchnum_count3__max,cardnum-merchnum_count3__sum,Fraud
0,1,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,...,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,0
1,2,31.42,31.42,31.42,31.42,31.42,31.42,31.42,31.42,31.42,...,31.42,31.42,31.42,31.42,31.42,31.42,31.42,31.42,31.42,0
2,3,178.49,178.49,178.49,178.49,178.49,178.49,178.49,178.49,178.49,...,178.49,178.49,178.49,178.49,178.49,178.49,178.49,178.49,178.49,0
3,4,3.62,3.62,3.62,7.24,3.62,3.62,3.62,3.62,3.62,...,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,3.62,0
4,5,3.62,3.62,3.62,10.86,3.62,3.62,7.24,3.62,7.24,...,3.62,7.24,3.62,3.62,7.24,3.62,3.62,3.62,7.24,0

In [7]:
independent = df[selected]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data=scaler.fit_transform(independent.to_numpy())
data=pd.DataFrame(data,columns=independent.columns)

In [9]:
for col in list(data.columns):
    a = np.array(data[col].values.tolist())
    data[col] = np.where(a > 5, 5, a).tolist()

In [10]:
data['Recnum'] = df['Recnum']
data['Fraud'] = df['Fraud']

In [11]:
data.info('')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96397 entries, 0 to 96396
Data columns (total 22 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Merch_description_part_count0__max           96397 non-null  float64
 1   Merchnum_count0__max                         96397 non-null  float64
 2   Merchnum_count1__max                         96397 non-null  float64
 3   Merchnum_count1__sum                         96397 non-null  float64
 4   Merchnum_count3__max                         96397 non-null  float64
 5   cardnum-merch_description_part_count14__max  96397 non-null  float64
 6   cardnum-merch_description_part_count14__sum  96397 non-null  float64
 7   cardnum-merch_description_part_count30__max  96397 non-null  float64
 8   cardnum-merch_description_part_count3__sum   96397 non-null  float64
 9   cardnum-merch_state_count14__max             96397 non-null  float64
 10  cardnum-merch_state_count30__max             96397 non-null  float64
 11  cardnum-merch_state_merch_zip_count30__max   96397 non-null  float64
 12  cardnum-merch_state_merch_zip_count3__sum    96397 non-null  float64
 13  cardnum-merch_zip_count14__max               96397 non-null  float64
 14  cardnum-merchnum_count14__max                96397 non-null  float64
 15  cardnum-merchnum_count14__sum                96397 non-null  float64
 16  cardnum-merchnum_count1__max                 96397 non-null  float64
 17  cardnum-merchnum_count30__max                96397 non-null  float64
 18  cardnum-merchnum_count3__max                 96397 non-null  float64
 19  cardnum-merchnum_count3__sum                 96397 non-null  float64
 20  Recnum                                       96397 non-null  int64
 21  Fraud                                        96397 non-null  int64
dtypes: float64(20), int64(2)
memory usage: 16.2 MB

In [12]:
data.to_csv('final_selected_variables.csv')

In [ ]:
data.